---
title: "h2"
author: "natashasanthanam"
date: "2020-10-28"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

Histogram and Summary Statistics for both Pvalues and H2 values generated by GCTA

Using this for loop, I generated the gcta output for all 256 phenotypes. I also ran the for loop again with the permuted phenotype file
```{sh eval=FALSE}
for i in {1..256}
do 
gcta --grm-bin /gpfs/data/im-lab/nas40t2/Data/GTEx/V8/genotype/plink_files/GTEX_grm_output --pheno /gpfs/data/im-lab/nas40t2/natasha/GTEX_Analysis/pheno_gtex_perm.txt --reml-no-constrain --out /gpfs/data/im-lab/nas40t2/natasha/GTEX_Analysis/perm_loop/gtex_output_perm_$i --thread-num 4 --mpheno $i
done
```


```{sh eval=FALSE}
library(workflowr)
library(tidyverse)
library(dplyr)
library(stringr)
DATA="/Users/natashasanthanam/Github/GTEX-Analysis"
```


Pvalues and H2 values for GCTA output
```{sh eval=FALSE}
pval = read_tsv(glue::glue("{DATA}/pval.txt" ), col_names = FALSE)
hist(pval$X2)
summary(pval$X2)

h2 = read_tsv(glue::glue("{DATA}/vgvp.txt"),col_names=FALSE)
summary(h2$X2)
t.test(h2$X2)
wilcox.test(h2$X2, h2_perm$X2, alternative = "two.sided")
hist(h2$X2)
```

Pvalues and H2 values for GCTA output generated using permuted phenotype file
```{sh eval=FALSE}
pval_perm = read_tsv(glue::glue("{DATA}/pval_perm.txt" ), col_names = FALSE)
h2_perm = read_tsv(glue::glue("{DATA}/vgvp_perm.txt" ), col_names = FALSE)

hist(pval_perm$X2)
summary(pval_perm$X2)

summary(h2_perm$X2)
t.test(h2_perm$X2)
hist(h2_perm$X2)

```

```{sh eval=FALSE}
pval_perm2 = read_tsv(glue::glue("{DATA}/pval_perm2.txt" ), col_names = FALSE)
h2_perm2 = read_tsv(glue::glue("{DATA}/vgvp_perm2.txt" ), col_names = FALSE)

hist(pval_perm2$X2)
summary(pval_perm2$X2)

summary(h2_perm2$X2)
t.test(h2_perm2$X2)
hist(h2_perm2$X2)
```

```{sh eval=FALSE}
mytest = function(x) 
{ x= x[!is.na(x)]
  print(binom.test(sum(x >0) , n=length(x), p=0.5) ) 
}
```


Reading in Constrain h2 values 
```{sh eval=FALSE}
h2_constrain = read_tsv(glue::glue("{DATA}/vgvp_constrain.txt" ), col_names = FALSE)
h2_perm_constrain = read_tsv(glue::glue("{DATA}/vgvp_perm_constrain.txt" ), col_names = FALSE)
h2_perm_constrain2 = read_tsv(glue::glue("{DATA}/vgvp_perm_constrain2.txt" ), col_names = FALSE)
```


```{sh eval=FALSE}
numextract <- function(string){ 
  str_extract(string, "\\-*\\d+")
} 
h2$X1 = numextract(h2$X1)
h2_perm$X1 = numextract(h2_perm$X1)
h2_perm2$X1 = numextract(h2_perm2$X1)

h2_constrain$X1 = numextract(h2_constrain$X1)
h2_perm_constrain$X1 = numextract(h2_perm_constrain$X1)
h2_perm_constrain2$X1 = numextract(h2_perm_constrain2$X2)

```


Not necessary - got sidetracked
write_tsv(h2_constrain, "/Users/natashasanthanam/Github/GTEX-Analysis/mergemee/h2_constrain", na = "-9", col_names = FALSE, quote_escape = "none")
write_tsv(h2_perm_constrain, "/Users/natashasanthanam/Github/GTEX-Analysis/mergemee/h2_perm_constrain", na = "-9", col_names = FALSE, quote_escape = "none")
write_tsv(h2_perm_constrain2, "/Users/natashasanthanam/Github/GTEX-Analysis/mergemee/h2_perm_constrain2", na = "-9", col_names = FALSE, quote_escape = "none")


mypath = '/Users/natashasanthanam/Github/GTEX-Analysis/mergemee'
multmerge = function(mypath){
filenames=list.files(path=mypath, full.names=TRUE)
datalist = lapply(filenames, function(x){read.csv(file=x,header=T)})
Reduce(function(x,y) {merge(x,y, by='X1', all=TRUE)}, datalist)
}
mergeh2 = multmerge('C://R//mergemee')



Create a file that contains h2 values of with constrain, no constrain, perm with constrain, perm without, perm2 with constrain and perm2 without constrain
```{sh eval=FALSE}

my.list = list(h2_constrain$X1, h2$X2, h2_perm$X2, h2_perm2$X2, h2_constrain$X2, h2_perm_constrain$X2, h2_perm_constrain2$X2)

new_data = data.frame(lapply(my.list, "length<-", max(lengths(my.list))))
colnames(new_data) <- c("Phenotype", "H2", "Perm1", "Perm2", "H2 constrained", "Perm constrained 1", "Perm Constrained 2")
new_data$Phenotype = str_sort(new_data$Phenotype, numeric = TRUE)

pivot_new = data.frame(pivot_longer(new_data, cols = starts_with("Perm"),
   names_to = "permutations",
   names_prefix = "perm",
   values_to = "rank",
   values_drop_na = TRUE))

write_tsv(new_data, file = 'df.GTEX.txt', na = "-9", col_names = TRUE, quote_escape = "none")
write_tsv(pivot_new, file = 'df.Pivot.txt', na = "-9", col_names = TRUE, quote_escape = "none")
```




